import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pitek- One Simple</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Page */}
      <div className={styles.bannerContainer}>
        <video loop muted autoPlay className={styles.bannerVideo}>
          <source src="/mp4/banner_fullhd.mp4" />
        </video>
        <div className={styles.bannerText}>Digital Product Development</div>
        <div className={styles.exploreMore}>
          <p>Explore more</p>
          <div className={styles.line}></div>
        </div>
      </div>
      <section className={styles.about}></section>
    </div>
  );
}
