import Image from "next/image";
import React, { useEffect, useState } from "react";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import styles from "../../styles/Project.module.scss";
import { useRef } from "react";
import withTransition from "../../HOC/withTransition";
import Head from "next/head";
import { useRouter } from "next/router";
import useWindowSize from "../../helper/useWindowSize";

const Ecoe = () => {
  const [showMenu, setShowMenu] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [showRedMenu, setShowRedMenu] = useState(false);
  const [showSnackBar, setShowSnackBar] = useState(false);

  const windowSize = useWindowSize();

  const topRef = useRef();

  const scrollTo = (ref) => {
    if (ref && ref.current) {
      ref.current.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  const router = useRouter();

  const [ogUrl, setOgUrl] = useState("");

  useEffect(() => {
    const host = window.location.host;
    const baseUrl = `https://${host}`;

    setOgUrl(`${baseUrl}${router.pathname}`);
  }, [router.pathname]);

  useEffect(() => {
    // let interVal = setInterval(() => {
    //   setShowSnackBar(false);
    // }, 1000);

    let timer = setTimeout(() => {
      if (showSnackBar) {
        setShowSnackBar(false);
      }
    }, 500);

    return () => clearTimeout(timer);
  }, [showSnackBar]);

  const handleCopyLink = () => {
    navigator?.clipboard?.writeText(ogUrl).then(() => setShowSnackBar(true));
  };

  const handleShowForm = () => {
    if (windowSize.width < 1025) {
      setShowForm(true);
    } else {
      setShowMenu(true);
      setShowForm(true);
    }
  };

  return (
    <>
      <Head>
        <title>Pitek- One Simple</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div
        className={`${styles.snackBar} ${
          showSnackBar ? styles.show : styles.hide
        }`}
      >
        Copied link to clipboard
      </div>
      <div className={styles.projectPage}>
        <Navbar
          showForm={showForm}
          setShowForm={setShowForm}
          showMenu={showMenu}
          setShowMenu={setShowMenu}
          showRedMenu={showRedMenu}
          setShowRedMenu={setShowRedMenu}
        />
        <div className={styles.projectContent}>
          <div className={styles.banner}></div>
          <div className={styles.projectInfo}>
            <div className={styles.title} ref={topRef}>
              <h1> Ecoe App</h1>
              <p>
                Real estate transaction platform with message “Real product -
                real value”. Ecoe App provides an all-in-one platform to connect
                investors, sales staff, home buyers and sellers. Thereby
                providing suitable solutions, contributing to the maximum
                efficiency of the transaction.
              </p>
            </div>
            <div className={styles.list}>
              <div className={styles.col}>
                <p>Client</p>
                <p className="font-12">Ecoe</p>
              </div>
              <div className={styles.col}>
                <p>Category</p>
                <p className="font-12">Real estate</p>
              </div>
              <div className={styles.col}>
                <p>Service</p>
                <p className="font-12">Software development </p>
                <p className="font-12">Business process solution</p>
              </div>
            </div>
            <div className={styles.categoryBlock}>
              <h3>Objective</h3>
              <p>
                The demand for information searching, buying and selling of Real
                Estate in the market is very large. However, there are many
                difficulties and limitations in the process of searching and
                accessing information between buyers and sellers. It takes a lot
                of time and effort to find a suitable product or customer.
              </p>
            </div>
            <div className={styles.categoryBlock}>
              <h3>Result</h3>
              <p>
                More than 10k consultations are made between consultants and
                customers through the app.
              </p>
              <p>
                Improve users experience, help users easy to work and search
                fastly, real estate transactions with binding information and
                become most exactly.
              </p>
            </div>
            <div className={styles.projectImage}>
              <Image
                src="/projects/ecoe_img_1.png"
                width={960}
                height={540}
                alt=""
              />
              <p>
                We drive the core value of a real estate searching and trading
                app must always be based on transparent and factual products.
                From there, we deploy censorship processes (eKYC online
                identity, the application supports product moderation...) and
                ensure the products on the application always have accurate
                information, legal clarity.
              </p>
            </div>
            <div className={styles.projectImage}>
              <Image
                src="/projects/ecoe_img_2.png"
                width={960}
                height={440}
                alt=""
              />
              <p>
                We drive the core value of a real estate searching and trading
                app must always be based on transparent and factual products.
                From there, we deploy censorship processes (eKYC online
                identity, the application supports product moderation...) and
                ensure the products on the application always have accurate
                information, legal clarity.
              </p>
            </div>
            <div className={styles.projectImage}>
              <Image
                src="/projects/ecoe_img_3.png"
                width={960}
                height={440}
                alt=""
              />
              <p>
                We drive the core value of a real estate searching and trading
                app must always be based on transparent and factual products.
                From there, we deploy censorship processes (eKYC online
                identity, the application supports product moderation...) and
                ensure the products on the application always have accurate
                information, legal clarity.
              </p>
            </div>
            <div className={styles.projectFooter}>
              <div className={styles.footerItem1}>
                <div
                  style={{ cursor: "pointer" }}
                  onClick={() => scrollTo(topRef)}
                >
                  <Image
                    src="/icons/to_top.svg"
                    width={24}
                    height={24}
                    alt=""
                  />
                </div>
                <div style={{ cursor: "pointer" }} onClick={handleCopyLink}>
                  <Image src="/icons/share.svg" width={24} height={24} alt="" />
                  {/* <span>Copied!</span> */}
                </div>
              </div>
              <div className={styles.footerItem2}>
                <div className="sub-title">Do you like this project ?</div>
                <button className="btn btn-red" onClick={handleShowForm}>
                  BRIEF US
                </button>
              </div>
            </div>
          </div>
        </div>
        {/* <Footer /> */}
      </div>
    </>
  );
};

export default withTransition(Ecoe);
